---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Malware Scan:
    malwareExecuteScan: false
  Acceptance:
    npmExecuteEndToEndTests: false
    cloudFoundryDeploy: false
  Compliance:
    sonarExecuteScan: false
  Release:
    tmsExport: false
    tmsUpload: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "f49fa7c3trial"
    cfSpace: "dev"
    cfCredentialsId: "cfdeploy"
    deployType: "standard"
    cloudFoundryDeploy: true
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
